---
- name: Install and start Nginx on Ubuntu
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        content: "<h1>Hello from Nginx deployed via Ansible by Mohan Shyam</h1>"
        dest: /var/www/html/index.html
